FROM eclipse-temurin:17-jdk-alpine
VOLUME /tmp
COPY *.jar authentication.jar
ENV JAVA_OPTS=" -Xshareclasses:name=cacheapp,cacheDir=/cache,nonfatal -XX:+UseContainerSupport -XX:MaxRAMPercentage=70 -Djava.security.egd=file:/dev/./urandom"
# Replace with a non-root authentication to avoid running the container with excessive privileges
USER appAuthentication
ENTRYPOINT [ "sh", "-c", "java $JAVA_OPTS  -jar authentication.jar" ]
