package com.creadiya.authentication.usecase.permission.enums;

public enum IntegerConstants {
  MAX_RESOURCE_LENGTH(50),
  MAX_ACTION_LENGTH(50),
  MAX_ROLE_NAME_LENGTH(30),
  MAX_ROLE_DESCRIPTION_LENGTH(256),
  MAX_TYPE_IDENTIFICATION_NAME_LENGTH(100),
  MIN_PASSWORD_LENGTH(8),
  MAX_PASSWORD_LENGTH(200),
  MIN_EMAIL_LENGTH(5),
  MAX_EMAIL_LENGTH(250),
  MIN_PHONE_LENGTH(7),
  MAX_PHONE_LENGTH(15),
  MIN_NAME_LENGTH(2),
  MAX_NAME_LENGTH(200),
  MAX_LAST_NAME_LENGTH(200),
  MIN_LAST_NAME_LENGTH(2),
  MAX_IDENTIFICATION_LENGTH(200),
  MAX_ADDRESS_LENGTH(200),
  MIN_BASE_SALARY_VALUE(1),
  MIN_IDENTIFICATION_LENGTH(2),
  MINIMUM_AGE(18)
  ;



  public final int value;

  IntegerConstants(int value) {
    this.value = value;
  }
}
